INSERT INTO Person (firstName, lastName, age, location_id)
VALUES ('Chickie', 'Ourtic', 21, 1),
       ('Hilton', 'O’Hanley', 38, 1),
       ('Barbe', 'Purver', 50, 3),
       ('Reeta', 'Sammons', 34, 2),
       ('Abbott', 'Fisbburne', 49, 1),
       ('Winnie', 'Whines', 20, 4),
       ('Samantha', 'Leese', 35, 2),
       ('Edouard', 'Lorimer', 30, 1),
       ('Mattheus', 'Shaplin', 27, 3),
       ('Donnell', 'Corney', 25, 3),
       ('Wallis', 'Kauschke', 28, 3),
       ('Melva', 'Lanham', 21, 2),
       ('Amelina', 'McNirlan', 22, 4),
       ('Courtney', 'Holley', 23, 1),
       ('Sigismond', 'Vala', 22, 4),
       ('Jacquelynn', 'Halfacre', 24, 2),
       ('Alanna', 'Spino', 25, 3),
       ('Isa', 'Slight', 32, 1),
       ('Kakalina', 'Renne', 26, 3);
